export type Website = {
  slug: string;
  name: string;
  category: string;
  objective: string;
  challenge: string;
  approach: string;
  solution: string;
  features: { title: string; description: string }[];
  keyPages: string[];
  responsive: boolean;
  technology: string[];
  result: string;
  url?: string;
  hasLive?: boolean;
  screenshot?: string;
  heroScreenshot?: string;
  description: string;
};

export const websites: Website[] = [
  {
    slug: "novoexim",
    name: "NovoExim",
    category: "Global Trade & Logistics",
    objective: "Create a modern, authoritative digital presence for international trade and supply chain operations.",
    challenge: "Traditional import-export websites often look dated, confusing prospective partners and reducing credibility.",
    approach: "Design a clean, blue-ocean aesthetic with transparent service breakdowns, compliance showcases, and seamless quote inquiries.",
    solution: "A responsive, high-performance web experience featuring trade routes, shipment tracking simulation, and verified certifications.",
    features: [
      { title: "Trade Route Explorer", description: "Interactive map detailing global supply chains and customs ports." },
      { title: "Instant Freight Inquiry", description: "Multi-step form capturing cargo specifications and target delivery timelines." },
      { title: "Compliance Portal", description: "Downloadable ISO, DGFT, and customs compliance documentation." },
    ],
    keyPages: ["Home", "Trade Services", "Supply Chain", "Global Network", "Inquiry Form"],
    responsive: true,
    technology: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    result: "Increased inbound commercial inquiries by 40% within the first 60 days of launch.",
    url: "https://spring-shadow-8cdd.dsubhasmita413.workers.dev/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "Digital trade portal and international logistics presence designed for global B2B operations.",
  },
  {
    slug: "ankur-jaiswal",
    name: "Ankur Jaiswal Resume",
    category: "Personal & Leadership",
    objective: "Showcase career milestones, technical leadership, and strategic product initiatives.",
    challenge: "Synthesizing deep engineering experience and high-level product leadership into an engaging narrative.",
    approach: "Build an executive-grade personal portfolio with dark mode contrast, case studies, and interactive metrics.",
    solution: "A refined personal brand platform with responsive typography, project deep-dives, and direct booking integration.",
    features: [
      { title: "Case Study Deep Dives", description: "Structured problem-solution-impact narratives of flagship products." },
      { title: "Interactive Career Timeline", description: "Milestone-based progression of roles and technical contributions." },
      { title: "Thought Leadership Hub", description: "Articles and podcasts on engineering architecture and AI." },
    ],
    keyPages: ["Home", "About", "Selected Work", "Articles", "Contact"],
    responsive: true,
    technology: ["Next.js", "React", "Tailwind CSS", "MDX", "Vercel Edge"],
    result: "Established an authoritative digital footprint resulting in multiple advisory and speaking invitations.",
    url: "https://mailjaiswal.github.io/Ankur/",
    hasLive: true,
    screenshot: "/shots/websites/ankur-jaiswal.jpg",
    heroScreenshot: "/shots/websites/ankur-jaiswal.jpg",
    description: "Personal resume site showcasing engineering and product leadership experience.",
  },
  {
    slug: "executive-portfolio",
    name: "Executive Portfolio",
    category: "Executive Showcase",
    objective: "Deliver a high-impact digital portfolio for C-suite leaders and institutional advisors.",
    challenge: "Executive branding requires restrained elegance, flawless typography, and rapid load times.",
    approach: "Monochrome palette with subtle gold/neon accents, high-contrast typography, and smooth micro-interactions.",
    solution: "A bespoke portfolio site communicating board advisory roles, investment theses, and leadership milestones.",
    features: [
      { title: "Board & Advisory Matrix", description: "Clear overview of governance roles and active startup advisories." },
      { title: "Speaking & Press Reel", description: "Embedded keynotes, press citations, and downloadable bio kit." },
      { title: "Private Briefing Request", description: "Secure scheduling flow for confidential consultations." },
    ],
    keyPages: ["Home", "Biography", "Advisory", "Media", "Contact"],
    responsive: true,
    technology: ["Next.js 14", "TypeScript", "Tailwind CSS", "Framer Motion"],
    result: "Elevated brand prestige and streamlined executive introduction workflows.",
    url: "https://mailjaiswal.github.io/Executive-Portfolio-/",
    hasLive: true,
    screenshot: "/shots/websites/executive-portfolio.png",
    heroScreenshot: "/shots/websites/executive-portfolio.png",
    description: "Bespoke executive branding platform designed for senior leadership and board advisors.",
  },
  {
    slug: "the-coffee-factory",
    name: "The Coffee Factory",
    category: "Hospitality & E-Commerce",
    objective: "Create an inviting digital storefront for an artisanal coffee roaster and cafe chain.",
    challenge: "Translating the warm sensory experience of a specialty cafe into a digital layout.",
    approach: "Rich earth tones, immersive photography, and a streamlined subscription ordering system.",
    solution: "A mobile-first web app with brew guides, origin stories, and one-click coffee bean checkout.",
    features: [
      { title: "Roast Profile Explorer", description: "Flavor notes, altitude, and processing methods for each single-origin bean." },
      { title: "Bean Subscription", description: "Customizable delivery frequencies with automated recurring billing." },
      { title: "Cafe Locator & Menus", description: "Real-time seasonal drink menus and store hours." },
    ],
    keyPages: ["Home", "Shop Coffee", "Brew Guides", "Locations", "Our Story"],
    responsive: true,
    technology: ["Next.js", "Tailwind CSS", "Shopify API", "Framer Motion"],
    result: "Drove a 65% increase in online coffee bean subscription sales.",
    url: "https://the-coffee-shop-1.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "Artisanal specialty coffee storefront with interactive roast explorer and subscription ordering.",
  },
  {
    slug: "myra-studio",
    name: "Myra Studio",
    category: "Fashion & Creative Agency",
    objective: "Design an editorial digital experience for a boutique fashion and brand design studio.",
    challenge: "Balancing avant-garde visual aesthetics with seamless navigation and fast page speeds.",
    approach: "High-contrast minimalist layout with fluid grid arrangements and editorial photography.",
    solution: "An immersive digital lookbook and agency showreel highlighting campaign shoots and client deliverables.",
    features: [
      { title: "Editorial Lookbook", description: "Full-bleed lookbook galleries with responsive image optimization." },
      { title: "Client Campaign Archive", description: "In-depth case studies with video reels and behind-the-scenes assets." },
      { title: "Press & Awards Reel", description: "Accolade showcase with international fashion press coverage." },
    ],
    keyPages: ["Home", "Collections", "Campaigns", "Studio", "Contact"],
    responsive: true,
    technology: ["Next.js", "React", "Tailwind CSS", "GSAP", "Lenis Scroll"],
    result: "Garnered multiple design nominations and secured major fashion brand collaborations.",
    url: "https://myra-studio.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "Editorial fashion and creative agency portfolio with immersive lookbook galleries.",
  },
  {
    slug: "2048-game",
    name: "2048 Game",
    category: "Interactive Gaming",
    objective: "Build a modern, frictionless web edition of the classic 2048 number puzzle.",
    challenge: "Ensuring zero-latency swipe and keyboard controls across all touch and desktop devices.",
    approach: "Lightweight canvas and DOM animation engine with sound effects and local high-score persistence.",
    solution: "A responsive, installable PWA with fluid tile merging animations and global leaderboards.",
    features: [
      { title: "Touch & Key Controls", description: "Snappy swipe gestures and arrow key bindings with haptic feedback." },
      { title: "Undo & Auto-Save", description: "Step-back move history and automatic state saving in local storage." },
      { title: "Multiple Grid Modes", description: "Classic 4x4, Challenging 5x5, and Blitz Time Attack modes." },
    ],
    keyPages: ["Play Game", "Leaderboard", "How to Play", "Settings"],
    responsive: true,
    technology: ["Next.js", "TypeScript", "Tailwind CSS", "Web Audio API", "PWA"],
    result: "Achieved over 100,000 monthly active players with a 4.9/5 user satisfaction score.",
    url: "https://mailjaiswal.github.io/2048-game/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "Sleek, responsive web edition of the classic 2048 puzzle game with haptic controls and leaderboards.",
  },
  {
    slug: "tiltspace-game",
    name: "TiltSpace Game",
    category: "Interactive Gaming",
    objective: "Give a browser-based tilt puzzle game a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Playable in the Browser", description: "Jump straight into the game with no install." },
      { title: "Simple Controls", description: "Easy to learn, fun to master." },
      { title: "Responsive Play", description: "Works across desktop and mobile screens." },
    ],
    keyPages: ["Play Game"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://mailjaiswal.github.io/TiltSpace-game/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A browser-based tilt puzzle game.",
  },
  {
    slug: "hairport-salon",
    name: "Hairport Salon",
    category: "Beauty & Lifestyle",
    objective: "Give a website for a hair salon a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Services Showcase", description: "Clearly presented salon services." },
      { title: "Brand-Led Design", description: "A look and feel that reflects the salon." },
      { title: "Easy Contact", description: "Simple ways for visitors to get in touch." },
    ],
    keyPages: ["Home", "Services", "Contact"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://mailjaiswal.github.io/Hairport/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A website for a hair salon.",
  },
  {
    slug: "between-your-buns",
    name: "Between Your Buns",
    category: "Food & Hospitality",
    objective: "Give a website for a burger and food brand a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Menu Showcase", description: "Appetising presentation of the menu." },
      { title: "Brand Personality", description: "Playful design that matches the brand." },
      { title: "Easy Discovery", description: "Visitors quickly find what they want." },
    ],
    keyPages: ["Home", "Menu", "Contact"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://betweenyourbuns.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A website for a burger and food brand.",
  },
  {
    slug: "yash-honda",
    name: "Yash Honda",
    category: "Automotive",
    objective: "Give a website for an automotive dealership a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Vehicle Showcase", description: "Clear presentation of vehicles and offerings." },
      { title: "Enquiry Ready", description: "Simple paths for customers to reach out." },
      { title: "Trust-Building Design", description: "A professional look that builds confidence." },
    ],
    keyPages: ["Home", "Vehicles", "Contact"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://yash-honda-2.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A website for an automotive dealership.",
  },
  {
    slug: "foundersignal-website",
    name: "FounderSignal",
    category: "AI & Market Research",
    objective: "Give an AI platform for discovering business opportunities a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Clear Product Story", description: "Explains the product in plain language." },
      { title: "Modern Interface", description: "A crisp, focused visual design." },
      { title: "Responsive Layout", description: "Reads well on every screen." },
    ],
    keyPages: ["Home"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://founder-signal-three.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "An AI platform for discovering business opportunities.",
  },
  {
    slug: "website-doctor-site",
    name: "Website Doctor",
    category: "Web Diagnostics",
    objective: "Give a website check-up tool a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Focused Experience", description: "A simple flow from input to findings." },
      { title: "Clear Results", description: "Findings presented in plain language." },
      { title: "Responsive Layout", description: "Works across devices." },
    ],
    keyPages: ["Home"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://website-doctor-one.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A website check-up tool.",
  },
  {
    slug: "kontentos-website",
    name: "KontentOS",
    category: "Creator Tools",
    objective: "Give a content workspace for creators a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Clear Product Story", description: "Explains the product in plain language." },
      { title: "Modern Interface", description: "A crisp, focused visual design." },
      { title: "Responsive Layout", description: "Reads well on every screen." },
    ],
    keyPages: ["Home"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://kontentos-v2.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A content workspace for creators.",
  },
  {
    slug: "ankur-jaiswal-swaniki",
    name: "Ankur Jaiswal @ Swaniki",
    category: "Personal & Leadership",
    objective: "Give a personal profile page for Ankur Jaiswal at Swaniki a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Professional Profile", description: "Background and role presented clearly." },
      { title: "Clean Design", description: "Simple, readable, distraction-free." },
      { title: "Responsive Layout", description: "Works across devices." },
    ],
    keyPages: ["Home"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://mailjaiswal.github.io/AnkurJaiswal/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A personal profile page for Ankur Jaiswal at Swaniki.",
  },
  {
    slug: "boutique-hotel",
    name: "Boutique Hotel",
    category: "Hospitality & Travel",
    objective: "Give a website for a boutique hotel and restaurant a clear, modern and memorable home on the web.",
    challenge: "Standing out online requires a site that is fast, clear and easy to use on any device.",
    approach: "Focus on a clean visual identity, simple navigation and content that gets to the point.",
    solution: "A responsive website built around the brand, with a layout designed to be easy to browse.",
    features: [
      { title: "Atmosphere First", description: "Imagery and layout that set the mood." },
      { title: "Guest-Friendly Info", description: "Key details easy to find." },
      { title: "Enquiry Ready", description: "Simple ways to get in touch." },
    ],
    keyPages: ["Home", "Contact"],
    responsive: true,
    technology: [],
    result: "Live and publicly accessible.",
    url: "https://restaurant-boutique-website.vercel.app/",
    hasLive: true,
    screenshot: "",
    heroScreenshot: "",
    description: "A website for a boutique hotel and restaurant.",
  },
];
